### ISSUE TITLE
Firebase AUTHENTICATION_FAILED on Huawei devices

### ISSUE THREAD

**Issue by fgnm** [firebase/quickstart-android#1054]
I use Firebase Cloud Messaging to receive notifications from my own server through firebase token [Ref. [https://firebase.google.com/docs/cloud-messaging/android/client](https://firebase.google.com/docs/cloud-messaging/android/client)]. The system works well but I've noticed (using Crashlytics) that on some devices Firebase SDK is unable to generate the token and returns `AUTHENTICATION_FAILED`.

To be clear, I can be quite sure that the device is connected to internet (because the app performs some network operations before request Firebase token), so unless negligible probability, internet is not the cause of the problem. I can notice that this happens only on some Huawei devices (not all however). Could be this a consequence of recent Google/Huawei news? (Users that has this problem regularly use Google Play store and download my app)

Is there a way to identify prior the problem and present to user that error? Can be this fixed in some way or it's a system failure that cannot be fixed?

The code to reproduce the issue is exactly the same provided in this [example](https://github.com/firebase/quickstart-android/tree/master/messaging), however in order to reproduce the bug you need an appropriate device.

**Comment by jehadmashhour** [comment]
@google-oss-bot 

Yes I have the same issue right now on some devices , check the following report:

`com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: Failed to get Firebase Instance ID token for fetch.	at c.i.c.r.a.m.a(com.google.firebase:firebase-config@@19.1.1:30)	at c.i.c.r.a.j.then(Unknown Source:4)	at com.google.android.gms.tasks.zzf.run(Unknown Source:3)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)	at java.lang.Thread.run(Thread.java:784)`
`Caused by: java.io.IOException: AUTHENTICATION_FAILED	at c.i.c.m.P.then(com.google.firebase:firebase-iid@@20.0.2:7)	at com.google.android.gms.tasks.zzd.run(Unknown Source:7)	... 3 more`
 
Notes :

- For example -> **FirebaseInstanceId -> d4XMk3XvKcc**  on Huawei DUB-LX1 .
-  Some of devices have the same issue -> Huawei DUB-LX1 , HUAWEI JKM-LX1 , Samsung SM-A750F , Samsung SM-J700H

**Comment by samtstern** [comment]
@jehadmashhour I apologize for my very delayed response here, I missed this issue.  As you know many Huawei devices run modified operating systems that often don't work properly with Google services.

However if you can reproduce this reliably please file a bug here:
https://github.com/firebase/firebase-android-sdk

**Comment by jeffdcamp** [comment]
I'm seeing this on a bunch of devices including Huawei, Samsung, and Kindle devices.  This was working before for us (we were not getting errors and remote config worked great) on these devices, but something changed in one of the newer releases of the Firebase libraries to cause this error.

**Comment by fgnm** [comment]
Agree, @samtstern this is not a bug only on Huawei devices. Huawei is the major, but I've received many reports from: Samsung, Xiaomi, Wiko and OnePlus

**Comment by samtstern** [comment]
Thanks @jeffdcamp  and @fgnm for the clarification.  Please file an issue on the Firebase Android SDK repo with as much info as you have so that our SDK engineers can look into this.  It's outside my expertise.

**Comment by jaanmurumets-sk** [comment]
We have reported issue to google https://issuetracker.google.com/issues/143413382 and there is acknowledge by Google of problem:

"We got information from Firebase support that this  AUTHENTICATION_FAILED error is caused by GPS (Google Play Services) but fix date is not clear yet."

**Comment by samtstern** [comment]
@jaanmurumets-sk let's keep the discussion over here:
https://github.com/firebase/firebase-android-sdk/issues/1286#issuecomment-595926516
