### ISSUE TITLE
dynamic link detecting issue

### ISSUE THREAD

**Issue by koushik16github** [firebase/quickstart-android#1082]
I've implemented firebase dynamic link for referral install, dynamic link is created using short link. When clicking on the link app is opening via playstore and install if not installed. But after install dynamic link is not detected, playstore giving open button instead continue button. If already installed dynamic link is working very fine. I'm testing on beta version for both end.

**Comment by samtstern** [comment]
@koushik16github since you're having an issue with your application in production I would suggest reaching out to Firebase Support:
https://firebase.google.com/support

Please provide them with as much debugging information as possible, when something is not working we need logs/code/etc to figure out why.
