### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by pmokkapati** [firebase/quickstart-android#1132]
![Screenshot_20200615-232059](https://user-images.githubusercontent.com/1531471/84951283-11073980-b0a5-11ea-95c8-1e8b738a8a15.png)
We already have an app - coupanda - https://play.google.com/store/apps/details?id=com.coupanda&hl=en on app store.
However when I try to sign up I get an error - "App is not authorized to use Firebase Authentication. Please verify the correct package name and SHA-1 are configured in the Firebase Console. [App validation failed]".
Since the app was approved and is in the App store why am I getting this Authentication error ?

**Comment by samtstern** [comment]
@pmokkapati since this is an issue with a live app in production please contact Firebase support:
https://firebase.google.com/support

Most apps use a different signing key in development and in production.  My guess is that you only added your development key to Firebase, you need to also add your production key:
https://firebase.google.com/support/guides/launch-checklist#update_your_connected_apps
