### ISSUE TITLE
Crash not working for kotlin version

### ISSUE THREAD

**Issue by 4tee** [firebase/quickstart-android#1202]
I just clone and run the sample app. Tested the crash:app in the emulator.

When the UI for crash sample is running, there is 2 options: Java and Kotlin. Using Java, when i click the button, i can see in firebase console that crash is detected.

However, when i attempted to do on Kotlin, it is not. I try with different firebase project (different json) to verify again. The result is the same. Java works, Kotlin doesn't.

Any suggestions? Thanks.

**Comment by rosariopfernandes** [comment]
@4tee Can you tell us whether you checked the "Catch Crash" CheckBox or not? Just so we can we can reproduce your issue accurately.

**Comment by 4tee** [comment]
@rosariopfernandes ... I unchecked it to make them crashed.

**Comment by rosariopfernandes** [comment]
@4tee I tried to reproduce your issue with no success. Both the Java and Kotlin apps are working for me.

Here's what it looks like in the Crashlytics Console:

![Screenshot from 2020-11-05 00-09-40 resized](https://user-images.githubusercontent.com/16766726/98173269-7e542380-1efb-11eb-833c-7c4bf0b9e772.png)

Notice that it says "4 events". Some of them are from the Java app, others from the Kotlin app. They've been grouped together because it's the same type of crash being thrown from the same class (`View.OnClickListener`).

If you'd like to go through each of the 4 grouped events, click on the issue and then you'll see the page bellow. Navigate through the events by clicking on the <kbd>></kbd> button shown on the top right corner of this image:

![Screenshot from 2020-11-05 00-10-18](https://user-images.githubusercontent.com/16766726/98173508-e60a6e80-1efb-11eb-90bb-d28c23debf37.png)

**Comment by 4tee** [comment]
@rosariopfernandes ... thanks a lot for following up. Yes, today, i try to run again and it works in both Java and Kotlin now. 😕 
Anyway, I will close this thread. Thanks a lot once again.

**Comment by samtstern** [comment]
@rosariopfernandes thanks for looking into this!
