### ISSUE TITLE
No pop up notification and sound when app killed / in background

### ISSUE THREAD

**Issue by HartzDev** [firebase/quickstart-android#128]
Hai,

i use firebase cloud messaging.  
i have the toturial, and it works.
notification pop up shown and sound , if app in foreground.
but when app killed or in background, i get the notif, but no pop up and sound.
do i need add some code ??

thx.

**Comment by misu-rg** [comment]
I have the same problem on my Honor 7

Android 5.0.2.

**Comment by kroikie** [comment]
@HartzDev what device are you using? Could it be something similar to what @misu-rg reported?

**Comment by HartzDev** [comment]
@kroikie sorry, for late response,
i use samsung J5.
i have look for option protected Apps in my device, but no result :(.

**Comment by kroikie** [comment]
Hi @HartzDev couple of clarifications:
- You should not receive messages when the app is stopped (killed).
- Since you are getting the pop up (I assume you mean display notification) when your app is in the foreground then it is likely that you are generating the notification yourself. Since notification messages are not displayed when the app is in the foreground.

Please add the following:
- How are you sending the notification, HTTP API (if so state request being used) or Firebase console?
- Some code would help here as well, you onMessageReceived maybe.

Also:
Do you see this same issue if you are using an emulator with Google services?

**Comment by HartzDev** [comment]
Hi,

i have do more digging, and find that for process in background, we set all from json.
so when i put parameter sound, my notif give sound.

thx for all help guys :D

**Comment by sirsendu-maity** [comment]
Hi HartzDev  

I am facing same problem please help

thanks

**Comment by tricksilver04** [comment]
This is very important. Most cases of this problem has got to do with the settings on your Android Phone. Like for example, my Xiaomi Phone has a Security app feature to enable/disable apps from auto-starting. It was blocking the FCM from restarting when the app is killed. I assume other android phones will have similar problems rooted from the Security feature that it is using.

**Comment by himalayaahuja** [comment]
Hi @kroikie I face the same issue , I need the notification to pop out and display when the app is killed or no longer active but only thing that happens is notification silently shows in systems tray and then i have to manually pull down to view it. what can we do about this? please help

**Comment by kroikie** [comment]
Hi @himalayaahuja if you are receiving the message but it is not displaying in they way that you want I would use a data-only message (no notification payload) and then in onMessageReceived I would build the notification locally.
