### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by Prasannnakumar** [firebase/quickstart-android#1304]
* Android device: realme
  * Android OS version: 10
  * Google Play Services version: 21.21. 16
  * Firebase/Play Services SDK version: 4.3.8
  
we are currently making an app where you can also login via your Google account or mobile phone number with Firebase. With the keytool I have already read my SHA-1 and stored it in the project settings of Firebase (I also read the SHA-1 value via Gradle in Android-Studio, of course, it's the same value as in Keytool.). When I test the app while debugging, logging in via Google or mobile phone number is not possible,

 but in case of my Team member its working properly. 
 
but in my Case
Error:
This app is not authorized to use Firebase Authentication. Please verify the correct package name and SHA-1/SHA-256 are configured in the Firebase Console. [A safety_net_token was passed]

**Comment by samtstern** [comment]
@Prasannnakumar for SHA-1 issues the best place is StackOverflow, this is not an issue with the quickstart app. However before I close the issue let me take a guess at what's happening.

Since you said "but in case of my Team member its working properly" this sounds like a debug keystore issue. Every computer has its own unique debug keystore with its own SHA1:
https://developer.android.com/studio/publish/app-signing#debug-mode

If you have many developers you probably want to store a debug keystore in your repository so that everyone's debug builds have the same SHA1:
https://coffeeandspace.com/keep-a-debug-keystore-in-your-repository/
