### ISSUE TITLE
Feature Request: sending data-only messages from Console

### ISSUE THREAD

**Issue by Svoka** [firebase/quickstart-android#139]
Hi!
It's seems that most confusing part when you trying FCM for Android is to implement message when app is in background.
In this realisation, people can't use this great console and finally replace GCM with FCM.

Any thoughts? Maybe you already have it in our plans and we're just some hours away from becoming the happiest developers in a world? 💯

**Comment by pompobit** [comment]
already contacted the support months ago asking the same feature. I really hope they implement it but I received a vague response at that time

**Comment by samtstern** [comment]
@Svoka @pompobit we're definitely tracking this request, it's something many of us want to see in the console.  I believe you got a "vague" response since we don't like to offer fixed timelines on any features (as you know, software development is unpredictable at times).

I am going to close this issue as it's not directly relevant to the quickstart, thanks for the feedback!

**Comment by pompobit** [comment]
@samtstern It wasn't a critic, I meant that we couldn't count on an exact prevision of the release date of this feature (if ever).
I'm sorry if it sounded rude, my english is everything but perfect!

**Comment by samtstern** [comment]
@pompobit I didn't take it as rude, no worries!  Thanks again for being involved.
