### ISSUE TITLE
Firebase Storage: pausing/resuming problem reopened

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-android#144]
We have just updated to Firebase 9.6.1 and the problem described here https://github.com/firebase/quickstart-android/issues/119 is still seen!

**Comment by samtstern** [comment]
@myflashlab this will actually be fixed in a later version, we have a pretty long lead time on releases (so we can test them a **lot**) and when you had reported #119 the `9.6.x` branch was already closed.  We're working every day to shorten this lead time.

Thanks for following up though!  I will comment on your original issues when the fix is released.
