### ISSUE TITLE
Firebase Notification Version Filter Not Working

### ISSUE THREAD

**Issue by iamayushjain** [firebase/quickstart-android#152]
### Problem:

I have been using Firebase Notification from the last 4 months for targeting my User Segments. 

Recently I tried using targeting a notification on a particular user segment, who are using the previous versions of the app, using Version Filter (Exact match) in additional Statements options by selecting the "AND" operator.

The notification was supposed to be targeted to the users who were using the previous version of the application.
**But instead the notification was delivered to all of my user segments,** i.e., both users using Previous and Current Versions of the application.

https://support.google.com/firebase/answer/6394759#segments

**Comment by samtstern** [comment]
This seems like something has gone wrong that's particular to your application, and possibly involving the FCM backend.  Since it's not a generalized issue or something to do with the code in this repository, please contact the personalized Firebase support service at: https://firebase.google.com/support/contact/troubleshooting

They'll be able to dig in to your project and hopefully find out what went wrong.
