### ISSUE TITLE
Firebase Messages Delay (Huge Delay)

### ISSUE THREAD

**Issue by vladimirarevshatyan** [firebase/quickstart-android#194]
Yesterday i encounter the horrible delay in the Firebase notification service.This has happened to both:console and from server,i have sent 10 messages in a row,5 from my own server and 5 from console,and the android device received it only after a long delay.This is first time i encounter this,yet it is horrible for me because i have no chance but to user Firebase,i tell you why.I am basically using Firebase to push a content into the device,generally and mainly for real-time chat and notifications,the issue is that the message will not be at all delivered if we have a delay,yet i understand that Firebase is a free to use service,but i know another thing,that the Firebase is Google's creation so there shall not be such things,as Google does everything purely perfect,i guess you should check sometime you'r servers and payloads seeing what causes so huge delay,and i am not talking about 30 minutes delay,but even more and greater.
Thank you for you'r time and patience.

**Comment by samtstern** [comment]
@vladimirarevshatyan thanks for the feedback.  FCM messages are not intended to have a huge delay so there's probably something strange going on in your setup.

#4 and #89 discuss general FCM issues, and #190 talks about the same issue you have.  Because this issue doesn't contain any technical information for debugging I am going to close it and suggest that we continue the discussion in one of those threads.
