### ISSUE TITLE
Feature Request: FLAG_INCLUDE_STOPPED_PACKAGES, Data Notifications do not wake up Killed Application

### ISSUE THREAD

**Issue by rcha** [firebase/quickstart-android#221]
Related to #4 and #89 as a feature request.

A developer needs to be able to receive the onMessageReceived() callback called when the app is killed.

For use cases where FCM is being used to send messages to the devices as Data Notifications and handling building the notifications themselves from the payload. 

There should be a way to specify so that the broadcast intent that FCM fires contains the FLAG_INCLUDE_STOPPED_PACKAGES set to true. 

This use case seems to work when using GCM, but FCM seems to set the FLAG_EXCLUDE_STOPPED_PACKAGES to true.

**Comment by 240ch** [comment]
It's often argued that users don't want an app to restart automatically after they killed it in the recents tray. I disagree and point out that users still want their Whatsapp, Facebook, Telegram etc. notifications to reach their phone. Even after a reboot, users don't want to start each app separately before being able to receive notifications. Therefore I really see this feature as a "must-have" for upcoming versions and use-cases. Developers want and need to communicate with the app in the background from time to time.

**Comment by samtstern** [comment]
@rcha @240ch thanks for the feedback here.  It's clear there would be value in what you propose, however this was considered by the FCM team a while ago and they decided on the current behavior.

Since this is just a quickstart repo we can't address this feature request here, so I'd suggest that you file it as a feature request here:
https://firebase.google.com/support/contact/bugs-features/

This will allow us to properly route it to the FCM folks who can give your request the consideration it deserves.  I am going to close this issue, hope that makes sense!

**Comment by mkosik** [comment]
Hello guys, any news regarding this feature or publicly accessible tracking of this feature request (if you filed it)?
@240ch regarding your on boot concern,  simple bootup receiver with intent action BOOT_COMPLETED specified in Manifest should be enough. System should register this receiver during app installation (because it's not in your code, but Manifest). Also, no part of your app could be executed without its process. Thus, after (re)boot, your app's process will be indeed started thanks to that receiver.
So by definition of app "stopped state" this affects only:
- when app is first installed, before something manually invokes a component (e.g., user launches an activity)
- after the user force-stops the app, until something manually invokes a component (e.g., user launches an activity)
For these cases, possibility to include FLAG_INCLUDE_STOPPED_PACKAGES would be much appreciated.

**Comment by rcha** [comment]
With the announcement of the upcoming GCM deprecation it worries me that this issue has not yet been resolved by Firebase. Can someone please escalate this to Google engineers as without this feature GCM to Firebase transition will be a breaking change.
