### ISSUE TITLE
Incorrect auth state listener message

### ISSUE THREAD

**Issue by opus1269** [firebase/quickstart-android#236]
* Android device: any
  * Android OS version: any
  * Google Play Services version: latest
  * Firebase/Play Services SDK version: 10.2.0
  
The following log message reports 0 listeners notified, but the last line is a log message from my listener. Happens on sign-in too.

```
D/FirebaseAuth: Notifying listeners about a sign-out event.
D/FirebaseApp: Notifying auth state listeners.
D/FirebaseApp: Notified 0 auth state listeners.
D/MyApp SignInActivity: onAuthStateChanged:signed_out

```

Not a big deal, but something for the TODO list.

**Comment by samtstern** [comment]
It's been a long time since the last update here so I am going to close this issue.  Thank you for reporting it and feel free to re-open if it you'd like to discuss further.

Additionally we now have two different listener types (`AuthStateListener` and `IdTokenListener`) which may help for your use case.
