### ISSUE TITLE
migrating from GCM and token scope issue

### ISSUE THREAD

**Issue by llooz** [firebase/quickstart-android#275]
I'm migrating an app from gcm sdk to the firebase sdk i have noticed that, by following the documentation and this quickstart, a new token is generated with a "*" scope without invalidating the old gcm token.

The result is that i have 2 valid token for the same device and so i will send a duplicated notification.

Currently i have solved the issue by forcing the GCM scope that is recommended to use on the gcm documentation and that i'm using on the current gcm version of the app:
`FirebaseInstanceId.getInstance().getToken(getString(R.string.gcm_defaultSenderId), "GCM");`

Am i doing something wrong? Is this an expected behavior?

**Comment by kroikie** [comment]
Hi @llooz the way you are handling the multiple valid tokens looks good. That way getToken will return the same token that GCM returned.

You could also consider removing extra tokens that have the same Instance ID, the part of the token before the colon (:). Since that will be the same for the same device whether you use "FCM" or "*" as the scope.
