### ISSUE TITLE
Unable to show image in notification when app is in backghround

### ISSUE THREAD

**Issue by shahzad1** [firebase/quickstart-android#284]
Hi, i am sending notifications to my android app using Firebase. Device is showing image in notification when the app is in foreground. But when the app is in background, it doesn't show image in notification, it only shows simple notification.

**Comment by kroikie** [comment]
Looks like you are sending a notification message from the console. In that case when your app is in the background you cannot dynamically update the image that is used with a notification message.

Since you cannot specify the notification icon in the console you can set the [default notification icon](https://firebase.google.com/docs/cloud-messaging/android/client#manifest) in your app's manifest.
