### ISSUE TITLE
Did Firebase Authentication Password-Based store in any database?

### ISSUE THREAD

**Issue by night-cypher** [firebase/quickstart-android#334]
Hi, how can I find where is the password store ?

**Comment by samtstern** [comment]
@night-cypher these are stored securely by Firebase, and there is no API to access the raw password if that's what you are asking for.

If you want to export all of the users, you can use the Firebase CLI:
https://firebase.google.com/docs/cli/auth#authexport

Closing this issue since it's not related to the Android quickstart.
