### ISSUE TITLE
Viewpager hard to swipe after adding maven { url 'https://maven.google.com'  }

### ISSUE THREAD

**Issue by night-cypher** [firebase/quickstart-android#335]
Hi, i have issue with tablayout viewpager and recyclerview. When i scrolling recyclerview I try to swipe to another tab, its **not able to swipe and need to wait around 3 second** only able to swipe or click item.

I figure out is the problem occur **after i adding maven { url 'https://maven.google.com'  } in my gradle.** When i remove it, the problem its gone !

How to fix this issue? thanksss

**Comment by samtstern** [comment]
@night-cypher adding the google maven repository can't possibly affect your runtime performance.  It only affects dependency resolution, which is a build/compile time consideration.

The only thing this could change is what version of the support libraries you resolve if you're declaring your dependencies with the `+` version notation.  In that case you should open an issue on the support lib issue tracker.

Closing this issue because as it is presented it's unrelated to Firebase or the code in this repo.
