### ISSUE TITLE
onTokenRefresh never fired on Galaxy S4/Android 5

### ISSUE THREAD

**Issue by 2ndGAB** [firebase/quickstart-android#339]
* Android device: Galaxy S4 Active
  * Android OS version: 5.0.1
  * Google Play Services version: 11.5.9
  * Firebase/Play Services SDK version: 11.0.4
  
### Step 3: Describe the problem:

After installing my application on different devices, I saw that it seems working correctly on Android 6 but I get blocked waiting for the token on few devices on Samsung S4 and J3, (at least).
I was able to debug on Galaxy S4 Active and saw that I was waiting for the token and the only way to receive it is to delete the instance id.

#### Steps to reproduce:

Install an application using Firebase   on Samsung Galaxy S4 Active Android 5.0.1

#### Observed Results:

  * What happened?  Nothing! wait for onTokenRefresh
  
#### Expected Results:

 onTokenRefresh() called.
  
#### Relevant Code:

  Same as given in your tuto, but if it doesn't come after 2 seconds after application starting, I peerform a `FirebaseInstanceId.getInstance().deleteInstanceId();` to get it fired.

**Comment by kroikie** [comment]
Hi @2ndGAB thanks for the issue. onTokenRefresh is only called when a brand new token is generated. If the app currently exists on the device reinstalling would not cause a new token to be generated.

If you are indeed doing a clean install of the app then you should expect to get a new token. You should not have to call deleteInstanceId in order to force a new token to be generated. Please confirm that this is what you are seeing on the latest SDK version (11.4.2)?

**Comment by samtstern** [comment]
It's been a while since any response here so I am going to close this issue.  @2ndGAB please comment if you still need help and we can re-open it!
