### ISSUE TITLE
.addOnCompleteListener vs. .addOnSuccessListener()

### ISSUE THREAD

**Issue by troy21688** [firebase/quickstart-android#369]
I am reading the Cloud Firestore documentation on how to get data, and I am seeing 2 listener types.

Can someone briefly explain the proper usage for each?

```
DocumentReference docRef = db.collection("cities").document("SF");
docRef.get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
    @Override
    public void onComplete(@NonNull Task<DocumentSnapshot> task) {
        if (task.isSuccessful()) {
            DocumentSnapshot document = task.getResult();
            if (document != null) {
                Log.d(TAG, "DocumentSnapshot data: " + task.getResult().getData());
            } else {
                Log.d(TAG, "No such document");
            }
        } else {
            Log.d(TAG, "get failed with ", task.getException());
        }
    }
});
```

vs.

```
DocumentReference docRef = db.collection("cities").document("BJ");
docRef.get().addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
    @Override
    public void onSuccess(DocumentSnapshot documentSnapshot) {
        City city = documentSnapshot.toObject(City.class);
    }
});
```

**Comment by samtstern** [comment]
@troy21688 thanks for asking, totally valid question.

The first thing to know is most Firebase Android SDKs use the `Task` API which you can read about here:
https://developers.google.com/android/guides/tasks

So when you call `docRef.get()` the result is a `Task<DocumentSnapshot>` where you can attach the listeners you're asking about.  These get called on the main thread when the action completes.

You can add as many listeners as you want to a single task, so the use of `OnSuccessListener` and `OnCompleteListener` are not mutually exclusive.  Feel free to add both.

There are basically four scenarios:

- Add a completion listener.  This makes sense when you have some common code you want to run for both success or failure.  For example, maybe you want to dismiss a "loading" dialog in either case.
- Add separate success / failure listeners.  This makes sense when your success/failure logic is totally separate.  The first example you posted above could have been done this way, since there's no overlap between the success/failure cases
- Add only a success listener.  This case is for tasks where your app will not do anything if it does not work, but may want to make note of success.
- Add only a failure listener. This is the case where your app does not have to do anything after success (like logging an event) but you would want to display an error in the case of failure.

Hope that helps!
