### ISSUE TITLE
writeNewUser is being called all the time not just for new users ?

### ISSUE THREAD

**Issue by ishandutta2007** [firebase/quickstart-android#374]
writeNewUser() is your [example](https://github.com/firebase/quickstart-android/blob/940ac4da5dd6cb212234abbc05d0fd54044fba52/database/app/src/main/java/com/google/firebase/quickstart/database/SignInActivity.java#L121
) is being call for all onAuthSuccess cases not just for new users.

How to figure out wheather the signedin user is new user or existing one?

**Comment by samtstern** [comment]
@ishandutta2007 we call this method for each sign in since it is safe to just overwrite the existing user with a new user.  But you're right, the name is confusing.

If you want to know which users are new, take a look at the `FirebaseUserMetadata` class:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUserMetadata

You can access it from `FirebaseUser`.  It has timestamps for sign up and sign in.  If they are the same, then the user is new.  If they are different, the user is just signing in again.

**Comment by ishandutta2007** [comment]
Someone gave me a [better solution](https://stackoverflow.com/a/47219371/865220) for firebase 11.6.0
