### ISSUE TITLE
MainActivity scrolls back to top position after coming back from RestaurantDetailActivity

### ISSUE THREAD

**Issue by thippesha** [firebase/quickstart-android#383]
On MainAcitivty If I scroll down and click on very bottom restaurant, RestaurantDetailActivity will open after hitting back or close button at RestaurantDetailActivity, the MainActivty scrolls back top position dispute I am scrolled to bottom and selected bottom one restaurant 

I tried to dev My own app and found the same issue MainActivity scrolls back to top position after coming back from RestaurantDetailActivity

and checked out FireStore app found the same mRestaurantsRecycler at MainActivity scrolls back to top position after coming back from RestaurantDetailActivity

is there any way to workaround to salve this

thank you

**Comment by samtstern** [comment]
@thippesha in this example app we begin listening to Firestore in `onStart` and remove the listener in `onStop`:

https://github.com/firebase/quickstart-android/blob/master/firestore/app/src/main/java/com/google/firebase/example/fireeats/MainActivity.java#L141

This means when the Activity goes out of sight we clear the recyclerview.  So when you navigate back to the activity it reloads the data (from cache, but still a reload) and forgets the position.

Could you try moving the `startListening()` and `stopListening()` calls to `onCreate` and `onDestroy` instead of `onStart` and `onStop` and see if you get the behavior you want?

It's also worth noting that throughout this repository you will see small UI "bugs" like this that were made in the name of simplicity.  This repo is not meant to demonstrate great Android app architecture, only a very simple Firebase integration!

**Comment by thippesha** [comment]
@samtstern Thanks, Sam Stern

As you stated above I modified the code and it's is working as expected 

> moving the startListening() and stopListening() calls to onCreate and onDestroy instead of onStart and onStop and see if you get the behavior you want?


**a Big thank you**

**Comment by samtstern** [comment]
@thippesha glad it worked!
