### ISSUE TITLE
Stop default notification that load in notification tray when app is killed?

### ISSUE THREAD

**Issue by zeeshansardar61** [firebase/quickstart-android#419]
I am receiving my data in background and through zzE method I m populating my custom notification, but with that custom notification, the default notification also pops up. I want to stop that? Can you please guide me. Thanks

**Comment by alizaidi606** [comment]
you need to send data only messages from server in order to stop default notification.
![image](https://user-images.githubusercontent.com/13392803/35900536-4a439660-0bf4-11e8-9b46-4ac7c0c35d3b.png)
as you can see here notification message is delivered to the device’s system tray when app is in background or killed. In order to customize that remove "notification" payload and send data only message in this case whether your app is in foreground, background or even killed notification will be delivered in onMessageReceived and you won't have to use zzE either.

**Comment by samtstern** [comment]
Thanks for the answer @alizaidi606.  That's correct, if you have a `notification` payload then the default background behavior is to create a notification.
