### ISSUE TITLE
Release build of perf example is broken

### ISSUE THREAD

**Issue by kurtisnelson** [firebase/quickstart-android#539]
Running ./gradlew assembleRelease against the performance example fails, seemingly due to proguard obfuscation or GMScore version drift.

My hunch is that something is wrong with the drop of GMScore from google3/integ into the SDK.

```
> Task :app:compileReleaseJavaWithJavac FAILED
~/quickstart-android/perf/app/src/main/java/com/google/firebase/quickstart/perfmon/MainActivity.java:64: error: cannot access zze
        mTrace.start();
              ^
  class file for com.google.android.gms.internal.firebase-perf.zze not found
```

None of these proguard rules fix it: 
```
-keep com.google.firebase.perf.metrics.**
-keepnames com.google.firebase.perf.metrics.**
-keepnames com.google.android.gms.internal.firebase-perf.**
-keep com.google.android.gms.internal.firebase-perf.**
```

**Comment by kurtisnelson** [comment]
I am running `./gradlew assembleRelease`

**Comment by samtstern** [comment]
@kurtisnelson I am able to run `./gradlew assembleRelease` on the `master` branch from both the root directory of this repo and the `perf` directory.

Maybe you've got something bad in your build cache?  This also is the kind of thing that Travis would catch in this repo, so I am a bit skeptical that there's a real problem here and it's more likely that one of us has a bad setup.

**Comment by samtstern** [comment]
I think this was a machine config issue, haven't heard any other reports.  Closing for now, happy to re-open if anyone else can repro.

**Comment by madlabman** [comment]
I have a similar issue. It caused by using Java 9 instead of 8.
