### ISSUE TITLE
Connect to Firebase failed

### ISSUE THREAD

**Issue by Awais914** [firebase/quickstart-android#582]
I will try to connect app to firebase in android studio but every time get error:
 **Firebase: Connect to Firebase failed. Please check your internet connection and try again.**
![error](https://user-images.githubusercontent.com/40486209/43730803-06de8578-99c6-11e8-904f-f63f6c259c99.PNG)

I searched the whole internet but cannot get solution.Is there any solution.?

**Comment by Awais914** [comment]
raojagannath11 i don't know why but firebase connected with in android studio on mobile hotspot internet connection, but failed on router connection.

**Comment by samtstern** [comment]
@Awais914 sounds like it really was an internet connection issue.  Due to that, closing this.

**Comment by alexjheck** [comment]
I am having the same issue and error message. I have checked my internet connection and everything is working fine. I have checked on different networks and still have the same issue. Also, when I upload the google-services.json file when manually attempting to sync Firebase with Android Studio project it tells me that the file does not belong to the project. I cannot find any more information on this.

**Comment by pruthil55** [comment]
I have faced same problem while connecting to firebase they are showing error message like please check your internet connection and i were tried it manually also but i can't connect so if any solution is there then please suggest me...

**Comment by jordangrant** [comment]
The first time I tried to link my account to Firebase, I had an out of date google-services.json so it failed to connect to my Firebase project. 

I then mistakenly went to myaccount.google.com and unlinked the Android Studio link in "Security" which was bad! because I could never link it back and received "Firebase: Connect to Firebase failed. Please check your internet connection and try again." No matter what.

I had to grab my other computer, clone the repo on it and get it running in Android Studio. Had to reinstall a lot of dependencies so it took a while. Next I re-downloaded googleservices.json from the Firebase Console and added it to my repo to make sure it was up to date. I signed out of google on Safari and Chrome. I ran my build on the device to make sure it was good to go.

Then finally, I pressed Connect to Firebase. It opened the browser to Google Login, I logged in with my google account (that I use for Firebase) and it worked. @pruthil55 

I'm using React Native by the way & react-native-firebase

**Comment by VISHALANONYMOUS** [comment]
just update your Android studio and restart your pc

**Comment by companyshot** [comment]
На русском: 
Наверное это будет уже поздно, но я решил эту проблему так. Зашел File ->  Settings -> Plugins, и обновил FIrebase Services После перезагрузил Android Studio
In English:
It will probably be too late, but I solved this problem this way. I went to File -> Settings -> Plugins, and updated FIrebase Services After I rebooted Android Studio
![Screenshot_1](https://user-images.githubusercontent.com/69414283/192447053-f79cfca6-7d06-430f-a8cf-8aef97df5c9a.png)
