### ISSUE TITLE
[Feature Request] Show last modified time in Firebase Storage

### ISSUE THREAD

**Issue by the-dagger** [firebase/quickstart-android#589]
Hi, opening an issue for another feature request in Firebase Storage. (Please do let me know in case there's a better way of doing this rather than creating an issue)

In firebase storage, the folders don't show the time when they were last modified or the size and hence as a result, it makes sorting and managing the data a very challenging task.

<img width="1186" alt="screenshot 2018-08-08 at 9 41 08 pm" src="https://user-images.githubusercontent.com/6565270/43850190-e3027afc-9b54-11e8-8131-6b340ad3d8c3.png">

The individual files however, do show the last modified time, so in theory this should be possible for folders as well.

<img width="940" alt="screenshot 2018-08-08 at 9 50 18 pm" src="https://user-images.githubusercontent.com/6565270/43850259-14a6b8e8-9b55-11e8-9ba0-e7b0d9ba4e1d.png">

**Comment by samtstern** [comment]
@the-dagger thanks for this.  When your feature request is not relevant to a particular platform (like the console UI one here) the best thing to do is to file a Feature Request in this form:
https://firebase.google.com/support/contact/

While I am not sure here, I think this one is surprisingly hard.  GCS doesn't really have "folders", it mostly just has objects that have paths that look like filesystem paths.  Some tools like `gsutil` and the Firebase console use this to make it appear filesystem-like.  Some more information here:
https://cloud.google.com/storage/docs/gsutil/addlhelp/HowSubdirectoriesWork

So I don't know if there's an efficient way to determine the last modified time of a folder since it would involve a recursive search.  But maybe I am wrong!

Closing this here since there's nothing that can be done in `quickstart-android`, please re-file with the form above if you have time.

**Comment by the-dagger** [comment]
Got it, thanks for the heads, I've filled up the form!
Also, the link you shared was a good read, I definitely learnt a thing or two. Thanks for that.
