### ISSUE TITLE
FCM onMessage() callback not received on specific phones

### ISSUE THREAD

**Issue by ckarthikv** [firebase/quickstart-android#70]
We're sending data-only payloads from the API to completely customize notifications, but specific phones never receive the onMessage callback.

Phones like the Xiaomi MI3, Redmi Note  and a lot of other Android phone models on Kitkat, get the callback 2/10 times, which is an abysmal rate for a "high-priority" message. But on higher end phones like OnePlus2, Nexus5, etc, the callbacks are received within 5 minutes mostly.

Any way around this? Why is the same codebase working on some phones and not working on a few?

**Comment by samtstern** [comment]
@ckarthikv I have heard other reports of issues with the Xiaomi and Redmi phones.  There are a number of possible device or connection specific reasons why you could be seeing this behavior, but it is certainly not the intentional behavior of the system.

This repository is just for issues with the quickstart sample, please contact the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/) for help with your issue.
