### ISSUE TITLE
Cannot "import from github" into Android Studio ... not set up for gradle

### ISSUE THREAD

**Issue by ErstwhileWork** [firebase/quickstart-android#71]
How should I import this project into Android Studio 2.2 (Preview 4 or later) and then use?

When importing, I get a complaint that the project is not set up to use gradle build, though I do see some gradle configuration information for different directories in the project.

Providing some directions in the overall README would be useful.

**Comment by samtstern** [comment]
@ErstwhileWork right now this repo is really a collection of separate gradle projects rather than one big project, so you should `git clone` the repo and then import one of the subfolders (`database`, `auth`, etc) into Android Studio.

I will investigate to see whether we can make a global grade config that would load all the projects at once.

**Comment by samtstern** [comment]
Fixed by #76, you should be able to import all projects at once now.
