### ISSUE TITLE
Database - why to duplicate posts?

### ISSUE THREAD

**Issue by fraggjkee** [firebase/quickstart-android#73]
I have installed the **database** sample and here is how it structures its data:

<img width="663" alt="2016-07-03 11 55 45" src="https://cloud.githubusercontent.com/assets/1222517/16544614/269a054c-4115-11e6-9ef1-f1d3fcfa969c.png">

I am not quite familiar with NoSQL techniques and trying to understand why we have to persist each `post` entity twice - at `posts` and `user_posts` correspondingly. The documentation says that this approach is called "Fan Out" and I fully agree that it might be useful to access user's posts via simple construction like `databaseReference.child("user-posts").child("<user_uid>")`. But why do we need the `posts` node then? What if we need to update some post - do we need to do it twice?

Thanks in advance and thank you for your great work guys 👍 

```java
    // [START write_fan_out]
    private void writeNewPost(String userId, String username, String title, String body) {
        // Create new post at /user-posts/$userid/$postid and at
        // /posts/$postid simultaneously
        String key = mDatabase.child("posts").push().getKey();
        Post post = new Post(userId, username, title, body);
        Map<String, Object> postValues = post.toMap();

        Map<String, Object> childUpdates = new HashMap<>();
        childUpdates.put("/posts/" + key, postValues);
        childUpdates.put("/user-posts/" + userId + "/" + key, postValues);

        mDatabase.updateChildren(childUpdates);
    }
    // [END write_fan_out]
```

**Comment by samtstern** [comment]
@fraggjkee the reason the posts are duplicated is because we want to be able to quickly get all the posts belonging to a user (as you suggested) and filtering from the list of all posts ever to get the posts by one user can get pretty expensive as the number of posts expands.

This does mean that we have to update the post in two locations whenever we update it.  It makes the code a little uglier but since queries are more common than writes it's better to optimize for reading the data.
