### ISSUE TITLE
Camera preview is horrible

### ISSUE THREAD

**Issue by wellbranding** [firebase/quickstart-android#745]
Camera preview is horrible. I have run tests on more than 100 devices and almost all of them uses lowest quality of camera preview. Also, camera source is not full size. Those two issues makes this project unavailable for our usage in a company. This is why we have to use other service providers. I hope Firebase team have a better version of this sample with **good camera preview on all devices.** Can you share it? I have discussed a lot with other developers locally and camera issues are number one factor for **not choosing ML Kit.**

**Comment by samtstern** [comment]
Thanks for the feedback!  These samples are not meant to always show Camera best practices since the Android Camera APIs are really hard and we want to make sure the MLKit code doesn't get lost in that complexity.  That said, we could probably do better.

@gkaldev can you help explain why we made the resolution tradeoffs in the sample?
@the-dagger do you have a favorite Camera library you can recommend to @wellbranding ?

**Comment by the-dagger** [comment]
Hi @samtstern, sure!
Hi @wellbranding, personally I've found https://github.com/natario1/CameraView to be a very good and fast camera library out there.

It works super well and also has support for frame processing for live processing, might want to give it a try!

**Comment by samtstern** [comment]
Going to close this issue as in the short term we don't plan to change the sample camera quality.  As @the-dagger said there are good libraries out there like `CameraView` that work well with ML Kit at high quality.
